# Generated by Django 3.2.3 on 2021-06-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_userreciperelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreciperelation',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
